### ISSUE TITLE
 Not executed rgee commands

### ISSUE THREAD

**Issue by hbermeo** [r-spatial/rgee#60]
* rgee version: 0.5.0
* R version: 3.6
* Operating System: windows 8

#### At submit an issue, please attached the following information of your `rgee` session:

- [x] You have the Python API installed (from terminal):
```
earthengine -h 
```

- [x] You can find the credentials file on your system: 
```r
library(rgee)
ee_path <- path.expand("~/.config/earthengine/credentials")
file.exists(ee_path)
```

- [ ] You can run a simple EE command from R: 
here starts the problem when I run some rgee command.

```r
library(rgee)

# Initialize the Earth Engine module.
ee_Initialize()

# Print metadata for a DEM dataset.
print(ee$Image('USGS/SRTMGL1_003')$getInfo())
``` 
Attach your Python (reticulate) configuration:

```r
library(reticulate)
py_config()
```

### Description

I think I have followed all the steps for the installation in windows. It even seems I get to start a session with rgee but when I want to execute a command I get the problem that I put above

### What I Did

```
> ee$String("Hello World from Earth Engine!")$getInfo()
 

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   AttributeError: 'NoneType' object has no attribute 'projects' 

```

**Comment by csaybar** [comment]
Hi, @hbermeo this problem arises when the Earth Engine session is not active, can you confirm that `ee_Initialize()` run successfully?

``` r
library(rgee)
ee_Initialize()
ee$String("hello world")$getInfo()
```

**Comment by hbermeo** [comment]
> ee_Initialize ()
-- rgee 0.5.0 --------------------------------------- earthengine-api 0.1.221 -- 
 √ email: not_defined
 √ Initializing Google Earth Engine:
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  EEException: Please authorize access to your Earth Engine account by running
earthengine authenticate
in your command line, and then retry. 

it appears that

**Comment by csaybar** [comment]
Could you run `list.files(path.expand("~/.config/earthengine"), full.names = TRUE)` and put the result here?

After run `ee_Initialize()` did not display a GUI to put a token?

**Comment by hbermeo** [comment]
> list.files(path.expand("~/.config/earthengine"), full.names = TRUE)
[1] "C:/Users/Holger Bermeo/Documents/.config/earthengine/a924da283165ded31d5fb98542b0974f_arqhbermeo@gmail.com"
[2] "C:/Users/Holger Bermeo/Documents/.config/earthengine/arqhbermeo"                                           
[3] "C:/Users/Holger Bermeo/Documents/.config/earthengine/credentials"                                          
[4] "C:/Users/Holger Bermeo/Documents/.config/earthengine/My First Project-cb3af1e09ca8.json"                   
[5] "C:/Users/Holger Bermeo/Documents/.config/earthengine/ndef"

**Comment by hbermeo** [comment]
using full credential

> > ee_Initialize(
>  email = "arqhbermeo@gmail.com",
>  drive = TRUE,
>  gcs = TRUE
>  )
> -- rgee 0.5.0 --------------------------------------- earthengine-api 0.1.221 -- 
>  √ email: arqhbermeo@gmail.com 
>  √ Google Drive credentials:  FOUND
>  √ GCS credentials:  FOUND
>  √ Initializing Google Earth Engine:Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   EEException: Please authorize access to your Earth Engine account by running
>  earthengine authenticate
>  in your command line, and then retry.
>  Detailed traceback: 
>  File "C:\Users\Holger Bermeo\Anaconda3\envs\ee\lib\site-packages\ee\__init__.py", line 114, in Initialize
>     credentials = data.get_persistent_credentials()
>   File "C:\Users\Holger Bermeo\Anaconda3\envs\ee\lib\site-packages\ee\data.py", line 240, in get_persistent_credentials
>     raise ee_exception.EEException(

**Comment by csaybar** [comment]
Everything looks good, It does not appear a problem of rgee. Could you run in Python and R the following:

In R:
```r
library(rgee)
ee$Initialize()
```
In Python:
```python
import ee
ee.Initialize()
```
I think the problem is that the credentials are saved successfully, but the Earth Engine Python API is not able to found it.

**Comment by hbermeo** [comment]
R

> library(rgee)
> ee$Initialize()
> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>  EEException: Please authorize access to your Earth Engine account by running
> 
> earthengine authenticate
> 
> in your command line, and then retry.
> 
> Detailed traceback: 
>   File "C:\Users\Holger Bermeo\Anaconda3\envs\ee\lib\site-packages\ee\__init__.py", line 114, in Initialize
>     credentials = data.get_persistent_credentials()
>   File "C:\Users\Holger Bermeo\Anaconda3\envs\ee\lib\site-packages\ee\data.py", line 240, in get_persistent_credentials
>     raise ee_exception.EEException(

Python
[https://drive.google.com/file/d/15dWQ3X0PGylUEvx_68Kfwo7VTADdSXic/view?usp=sharing](url)

**Comment by csaybar** [comment]
Thanks a lot for reporting this. The problem is that rgee is saving your credentials in:
>> C:/Users/Holger/Bermeo/Documents/.config/earthengine/arqhbermeo

while the Earth Engine Python API is seeking in:

>> C:/Users/Holger/Bermeo/.config/earthengine/arqhbermeo

I'm not 100% sure that this is a problem with rgee. But, to avoid this doubtfulness, whether or not it's a problem with rgee, I'm gonna leave all the Initialization module in the Python side.

If you are still interested in using rgee you could change your path manually, this should solve the problem temporarily. Let me know if the problem persists!

**Comment by hbermeo** [comment]
Trying to do it manually means copying the credentials to the folder that python is looking for, but I still get other errors. I don't know if it is a python installation problem in the end?

**Comment by csaybar** [comment]
rgee wraps a Python session in an R session. If the Earth Engine Python API does not work, rgee will not work in R either.

**Comment by csaybar** [comment]
We make important changes in the latest version of rgee (0.6.0 >) that make easier the installation process. I going to close the issue but feel free to reopen if you consider is necessary!.
