### ISSUE TITLE
GPM-IMERG dataset retrieved at wrong resolution 

### ISSUE THREAD

**Issue by daniel-althoff** [r-spatial/rgee#64]
* rgee version: 0.6.1
* R version: 4.0.1
* Operating System: Windows 10

#### At submit an issue, please attached the following information of your `rgee` session:

Attach your Python (reticulate) configuration:
```r
library(reticulate)
py_config()
```
python:         C:/Users/danie/Anaconda3/envs/rgee/python.exe
libpython:      C:/Users/danie/Anaconda3/envs/rgee/python38.dll
pythonhome:     C:/Users/danie/Anaconda3/envs/rgee
version:        3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 16:59:10) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/danie/Anaconda3/envs/rgee/Lib/site-packages/numpy
numpy_version:  1.18.5
ee:             C:\Users\danie\Anaconda3\envs\rgee\lib\site-packages\ee\__init__.p

NOTE: Python version was forced by RETICULATE_PYTHON

### Description

I'm trying to retrieve data from NASA/GPM_L3/IMERG_V06 dataset (https://developers.google.com/earth-engine/datasets/catalog/NASA_GPM_L3_IMERG_V06) and summarize them for a watershed. As they are half-hourly and in mm/hr, I sum them over the period of interest and divide by 2 (OK so far!).
When I add Layer to Map... it shows the GPM-IMERG data in a coarse resolution instead of 0.1° (~10 km). It is presenting data in approx. 1° (~100 km). I even checked the resolution, as shown bellow.
From GEE on chrome all works well. I can't figure out why the resolution is wrong on rgee.

### What I Did

```
library(rgee)
library(dplyr)
library(sf)
library(rgdal)
ee_Initialize()
centroid <- readOGR('G:/My Drive/Bases de dados/Shapes/biomas_5000_cerrado.shp') %>% rgeos::gCentroid()
mask <- readOGR('G:/My Drive/Bases de dados/Shapes/biomas_5000_cerrado.shp') %>%
  st_as_sf() %>% st_set_crs(4326) %>%  sf_as_ee()

gpm_imerg <- ee$ImageCollection('NASA/GPM_L3/IMERG_V06')$
  filterDate('2018-01-01', '2018-02-01')$
  map(function(x) x$reproject("EPSG:4326")$select("precipitationCal"))$
  reduce(ee$Reducer$sum())$
  divide(2)

Map$setCenter(-49, -14, 4)
Map$addLayer(gpm_imerg, visParams = list(min = 0, max = 440), name = 'GPM-IMERG')
## The Viewer works perfectly; however, the gridcells' size are close to 100 km . Instead, 0.1° should be close to 10 km.

gpm_imerg$projection()$nominalScale()$getInfo()
>> [1] 111319.5 
## 111319.5 is close to 1° and not 0.1°

```

**Comment by csaybar** [comment]
I don't know if in javascript this works but you will get the same results in Python. After applying a reduction to an ImageCollection, projection properties will lose. 

What you do:
```r
gpm_imerg <- ee$ImageCollection('NASA/GPM_L3/IMERG_V06')$
  filterDate('2018-01-01', '2018-02-01')$
  # Never use reproject in a map, it is computationally inefficient
  # https://developers.google.com/earth-engine/projections
  map(function(x) x$reproject("EPSG:4326")$select("precipitationCal"))$
  reduce(ee$Reducer$sum())$
  divide(2)
```
I would do the following to solve the problem:
```r
imerg_dataset <- ee$ImageCollection('NASA/GPM_L3/IMERG_V06')
gpm_imerg <- imerg_dataset$
  filterDate('2018-01-01', '2018-02-01')$
  map(function(x) x$select("precipitationCal"))$  
  reduce(ee$Reducer$sum())$ # you loss projection here
  divide(2)

Map$setCenter(-49, -14, 4)
Map$addLayer(gpm_imerg, visParams = list(min = 0, max = 440), name = 'GPM-IMERG')

# If the projection is still important run:
ee_help(gpm_imerg$reproject)
geotransform <- imerg_dataset$first()$projection()$getInfo()$transform
print(gpm_imerg$reproject("EPSG:4326", geotransform)$projection()$nominalScale()$getInfo())
print(gpm_imerg$projection()$nominalScale()$getInfo())
```

**Comment by daniel-althoff** [comment]
I knew I was letting some tiny detail go by.
Thank you very much, worked perfectly.

If it is not too inconvenient, I have a few further questions. 
1. How can I perform the "reduce(ee$Reducer$sum())$divide(2)" grouped by day?

2. Is there a way to import the results as a raster to R? or do I always have to export to a drive folder first?

**Comment by csaybar** [comment]
I had the same problem with ee_extract in the last versions of the earthengine-api. I will study a deeper the changelog on the weekend. 

With respect to your questions, You can found a [nice implementation](https://gis.stackexchange.com/questions/340193/precipitation-data-for-one-day-instead-of-3-hourly-data-from-trmm-in-google-eart) in javascript, I adapted to R:

```r
library(rgee)
library(dplyr)
library(sf)
library(rgdal)

ee_Initialize(drive = TRUE)

# Define a study area
arequipa <- st_read(system.file("shp/arequipa.shp", package = "rgee"))
ee_arequipa <- arequipa %>% 
  st_bbox() %>% 
  st_as_sfc() %>% 
  sf_as_ee() %>% 
  ee$FeatureCollection$geometry()

# Define start and end ee.Dates.
startDate <- ee$Date('2018-01-01')
endDate <- ee$Date('2018-01-10')

# Define a base collection.
gpm_imerg <- ee$ImageCollection('NASA/GPM_L3/IMERG_V06')$
  filterBounds(ee_arequipa)$
  filterDate(startDate, endDate)$
  map(function(img) img$
        select("precipitationCal")$
        divide(2)$
        clip(ee_arequipa)$
        copyProperties(img, list('system:id', 'system:time_start','system:time_end'))
  )

# Calc number of days between start and end dates.
nDays <- ee$Number(endDate$difference(startDate, 'day'))

# Enumerate a list of days.
daysList <- ee$List$sequence(0, nDays$subtract(1))

# Map over the list of days to make daily sum composites.

daily_aggregate <- function(dayN) {
  t1 <- startDate$advance(ee$Number(dayN), 'day')
  t2 <- t1$advance(1, 'day')
  dailySum <- gpm_imerg$filterDate(t1, t2)$sum()
  nBands <- dailySum$bandNames()$size()
  dailySum$set(
    list(
    'system:time_start' = t1$millis(),
    'nBands' = nBands
    )
  )
}
pcpDayList <- ee$ImageCollection(daysList$map(ee_utils_pyfunc(daily_aggregate)))

#Export Results to read in R
gpm_daily <- ee_imagecollection_to_local(
  ic = pcpDayList, 
  region = ee_arequipa,
  scale = 11131.95
)
plot(raster::stack(gpm_daily))

```

**Comment by daniel-althoff** [comment]
This implementation works great! Thank you very much!
I also noticed that there still seems to be inconsistencies with the extraction of values, but they are negligible now.

```r
ee_extract(x = pcpDayList, y = ee_mask, fun = ee$Reducer$mean(), sf = FALSE) %>% round(2)
raster::extract(raster::stack(gpm_daily), mask, mean) %>% round(2)
```
>> 8.83 14.20 12.34 17.08 24.61 21.96 6.99 2.35 0.07
>> 8.80 14.37 12.17 17.27 24.54 21.87 7.02 2.33 0.05

I'll close the issue since it has been resolved.

**Comment by rt10934** [comment]
I saw that you tried to import the "GPM" data in the daily frequency, I have the same problem, but I need to collect it by geographic coordinates, I already tried several codes, but in the end it gives an error or it still continues to import in the frequency every half hour, if you have any solution I would be very grateful.

code I'm trying to implement: 

`library(rgee)
# Retrieving data from weather stations:
Catalogoea <- readr::read_delim("C:/Doutorado/Artigos/Risco climatico/modelo/risco-climatico/Catalogoea.csv", 
                                delim = ";", escape_double = FALSE,
                                locale = readr::locale(decimal_mark = ",",
                                                       grouping_mark = "."),
                                trim_ws = TRUE)
# Filtering for the states of analysis:
Catalogoea <- Catalogoea |>
  dplyr::filter(SG_ESTADO %in% c("PR", "SC", "RS"))
# Selecting meteorological bases that had data collection started before 2010:
Catalogoea <- Catalogoea |>
  dplyr::mutate(Ano = lubridate::year(lubridate::dmy(DT_INICIO_OPERACAO)))
Catalogoea <- Catalogoea |>
  subset(Ano <= 2009)
# Create a FeatureCollection from the points
points <- lapply(seq_len(nrow(Catalogoea)), function(i) {
  row <- Catalogoea[i, ]
  point <- ee$Geometry$Point(row$VL_LONGITUDE, row$VL_LATITUDE)
  feature <- ee$Feature(point, list(CD_ESTACAO = row$CD_ESTACAO))
  feature
})
# Create a FeatureCollection from the list of points
ee_fc <- ee$FeatureCollection(points)
# Define the Image Collection "NASA/GPM_L3/IMERG_V06" and filter by date
IMERG <- ee$ImageCollection("NASA/GPM_L3/IMERG_V06")$filterDate("2012-12-30", "2012-12-31")
# Define a function to calculate the daily precipitation sum
sum_precipitation_daily <- function(image) {
  # Define the image date
  date <- ee$Date(image$get("system:time_start"))
  
  # Filter images within the same day
  start_date <- date$format("YYYY-MM-dd")
  end_date <- date$format("YYYY-MM-dd")
  daily_images <- IMERG$filterDate(start_date, end_date)
  
  # Filter images within the same hour of the day
  start_time <- date$format("HH:mm:ss")
  end_time <- date$format("HH:mm:ss")
  daily_images <- daily_images$filter(ee$Filter$And(
    ee$Filter$gte("system:time_start", start_time),
    ee$Filter$lt("system:time_start", end_time)
  ))
  # Calculate the daily precipitation sum
  daily_sum <- daily_images$sum()
  
  # Return the original image with the "precipitation" property set as the daily sum
  return(image$set("precipitationCal", daily_sum))
}

# Map the function to each image in the Image Collection
IMERG_daily_sum <- IMERG$map(sum_precipitation_daily)

# Select the "precipitation" band in the processed images
precip_IMERG <- IMERG_daily_sum$select("precipitationCal")

# Convert the FeatureCollection into a list of points and precipitation data
points_list <- ee_extract(precip_IMERG, ee_fc, fun = ee$Reducer$mean(), sf = F)
`
